#!/bin/bash
# This is HELL. I need to make some cleanup ..

#ZONES=${ZONES:-''}
#ZONES_DNSSEC=${ZONES_DNSSEC:-''}
#TSIG_KEYS=${TSIG_KEYS:-''}
#TSIG_SLAVES=${TSIG_SLAVES:-''}

[[ -d /var/lib/knot/zones/ ]] || mkdir /var/lib/knot/zones/
if [ ! -e /.bootstraped ]; then
  render.py /etc/knot/knot.conf.jinja2 > /etc/knot/knot.conf
  for zone in ${ZONES_DNSSEC}; do
    echo "adding signed zone $zone"
    cp /etc/knot/zones/${zone} /var/lib/knot/zones/$zone
  done
fi
touch /.bootstraped


echo "config dump:"
cat /etc/knot/knot.conf
chown -R knot: /var/lib/knot 
exec /usr/bin/knotd
